version: '3'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_MULTIPLE_DATABASES=ts_api,ts_api_test
      - POSTGRES_PASSWORD=postgres 
    ports:
      - "5432:5432"